_commit: 2.0.0
_src_path: gl:lksch-group/deploy-docker-compose-template
ansible_defaults_prefix: ph_
compose_file_path: docker-compose.yml
docker_user: dockerusr
docker_user_id: 1002
galaxy_author: PonyM
galaxy_role_namespace: gh_ponym
galaxy_tags: []
github_user: gh-PonyM
license: MIT license
min_ansible_version: '2.1'
min_secret_length: 17
molecule_distros:
- ubuntu2204
- debian12
molecule_docker_test: true
project_description: Generated ansible role docker using docker compose for ansible_docker_pihole
project_name: ansible_docker_pihole
proxy_container_net_attach: ''
remove_cli_artefact: true
role_name: ansible_docker_pihole
secret_provider: passwordstore
secret_string_template: services/{role_name}/{service_name}/{env_key}
standalone_role: true
user_company: ''
user_email: dev@lksch.ch
user_name: PonyM
