---
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - project: lksch-group/gitlab-ci-templates
    ref: main
    file: /python.yml
  - project: lksch-group/gitlab-ci-templates
    ref: main
    file: default-workflow-rules.yml
  - project: lksch-group/gitlab-ci-templates
    ref: main
    file: molecule.yml

stages:
  - lint
  - test

yamllint:
  extends: .python-poetry
  stage: lint
  script:
    - poetry run yamllint .
  rules:
    - changes:
        - "**/*.{yml,yaml}"

molecule:
  extends: .molecule-alpine
  stage: test
  parallel:
    matrix:
      - MOLECULE_DISTRO:
          - debian9
          - debian10
          - debian11
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
