---
- hosts: localhost
  vars:
    ph_custom_cache_size: 10000
    ph_dhcp_active: false
    ph_dnssec: true
    ph_dns_bogus_priv: true
    ph_dns_fqdn_required: true
    ph_ftlconf_local_ipv4: localhost
    ph_ipv6: true
    ph_pihole_dns: 9.9.9.9;9.9.9.10
    ph_pihole_gid: 1000
    ph_pihole_uid: 1000
    ph_tz: Europe/Berlin
    ph_virtual_host: localhost
    ph_webpassword: "{{ lookup('community.general.passwordstore', 'services/ansible_docker_pihole/pihole/WEBPASSWORD create=true length=47') }}"
    ph_webtheme: default-dark
    ph_host_port_pihole_53: 53
    ph_host_port_pihole_80: 80
    ph_releases:
      pihole: "latest"

    ph_pihole_mount_dir: "./etc-pihole"
    ph_dnsmasq_d_mount_dir: "./etc-dnsmasq.d"
    # backups
    borgbackup_include:
    - ./etc-pihole
    - ./etc-dnsmasq.d
    # ansible deploy defaults
    ph_user: dockerusr
    ph_user_id: 1002
    ph_ext_net: proxy-tier
    ph_project_name: ansible_docker_pihole
  roles:
  - role: docker
    tags: docker
  - role: ansible_docker_pihole
    tags: ansible_docker_pihole
