---

- name: Ensure deployment user for ansible_docker_pihole
  user:
    name: "{{ docker_deployment_user }}"
    state: "{{ ph_state | default('present') }}"
    create_home: true
    uid: "{{ docker_deployment_user_id }}"
    shell: /bin/bash

- name: Ensure user is added to the docker group.
  user:
    name: "{{ docker_deployment_user }}"
    groups: docker
    append: true

- name: Ensure repository paths are present
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_deployment_user }}"
    group: "{{ docker_deployment_user }}"
  become: true
  loop:
   - "{{ ph_repository_src }}"
   - "{{ ph_repository_src }}/scripts"

- name: Check if docker-compose.yml exists
  stat:
    path: "{{ ph_repository_src }}/docker-compose.yml"
  register: compose

- name: test docker-compose changed
  template:
    src: "docker-compose.yml"
    dest: "{{ ph_repository_src }}/docker-compose.yml"
    owner: "{{ docker_deployment_user }}"
    mode: "600"
  check_mode: true
  notify: ph_service_stop
  when: compose.stat.exists

- meta: flush_handlers

- name: Copy docker-compose.yml
  template:
    src: "docker-compose.yml"
    dest: "{{ ph_repository_src }}/docker-compose.yml"
    owner: "{{ docker_deployment_user }}"
    group: "{{ docker_deployment_user }}"
    mode: "600"

- include_tasks: run_cmds.yml
  vars:
    cmds: "{{ ph_pre_startup_commands }}"
    remove_script: "{{ ph_pre_startup_script_remove }}"
    script_content: "{{ ph_pre_startup_script }}"
    script_name: pre_startup.sh
  when: ph_state == 'present'

- name: legacy | Ensure services are {{ ph_state }}
  community.docker.docker_compose:
    project_name: "{{ ph_project_name }}"
    project_src: "{{ ph_repository_src }}"
    debug: true
    state: "{{ ph_state }}"
    build: false
    files:
      - docker-compose.yml
  become_user: "{{ docker_deployment_user }}"
  when:
    - compose_v1

# Requires community.docker >= 3.8.0. ansible-galaxy does not handle collection dependencies in roles meta/main.yml
- name: Ensure services are {{ ph_state }}
  community.docker.docker_compose_v2:
    project_name: "{{ ph_project_name }}"
    project_src: "{{ ph_repository_src }}"
    state: "{{ ph_state }}"
    files:
      - docker-compose.yml
  become_user: "{{ docker_deployment_user }}"
  when:
    - not compose_v1

- include_tasks: run_cmds.yml
  vars:
    cmds: "{{ ph_post_startup_commands }}"
    remove_script: "{{ ph_post_startup_script_remove }}"
    script_content: "{{ ph_post_startup_script }}"
    script_name: post_startup.sh
  when: "{{ ph_state == 'present' }}"

- name: Put auto-update script
  copy:
    content: |
      #!/usr/bin/env bash
      
      set -eu
      cd {{ ph_repository_src }}
      docker compose pull
      docker compose up -d

    dest: "{{ ph_repository_src }}/autoupdate.sh"
    owner: "{{ docker_deployment_user }}"
    group: "{{ docker_deployment_user }}"
    mode: "770"
  when: ph_auto_update

- name: Set auto-update cron to {{ cron_state }}
  cron:
    name: update all services for ansible_docker_pihole
    job: "{{ ph_repository_src }}/autoupdate.sh"
    hour: "{{ ph_auto_update_cron_hour }}"
    minute: "{{ ph_auto_update_cron_minute }}"
    weekday: "{{ ph_auto_update_cron_weekday }}"
    month: "{{ ph_auto_update_cron_month }}"
    user: "{{ docker_deployment_user }}"
    state: "{{ cron_state }}"
  become_user: "{{ docker_deployment_user }}"
  vars:
    cron_state: "{{ 'present' if ph_auto_update else 'absent' }}"
