---

- name: ensure compose setup is stopped
  community.docker.docker_compose:
    project_name: "{{ ph_project_name }}"
    project_src: "{{ repository_src }}"
    debug: true
    state: absent
  become_user: "{{ ph_user }}"

- name: Ensure repository path is absent
  file:
    path: "{{ repository_src }}"
    state: absent
